### ISSUE TITLE
Source view button

### ISSUE THREAD

**Issue by cleveHEX** [SoMainline/docs.somainline.org#3]
`View page source` button at the top right corner forwards to an [internal location](https://docs.somainline.org/_sources/platform/msm8994/sony/suzuran/index.rst.txt), but I think it should point to GitHub instead.

**Comment by ix5** [comment]
The docs are generated using [sphinx-doc](https://www.sphinx-doc.org/en/master/). Feel free to open a pull request to add/change a template to let the link point to GitHub.
